//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestHorizonWebService.HorizonServiceDevo {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HorizonServiceDevo.HorizonServiceSoap")]
    public interface HorizonServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CategoryList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseData))]
        TestHorizonWebService.HorizonServiceDevo.CategoryResponse CategoryList(string pUser, string pPassword, string pCustno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AliveCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseData))]
        TestHorizonWebService.HorizonServiceDevo.Response AliveCheck();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Items", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseData))]
        TestHorizonWebService.HorizonServiceDevo.ItemsInCategoryResponse Items(string pCategoryId, string pUser, string pPassword, string pCustno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Item", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseData))]
        TestHorizonWebService.HorizonServiceDevo.SingleItemResponse Item(string pItemId, string pUserId, string pPassword, string pCustno);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CategoryResponse : Response {
        
        private CategoryCollection detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CategoryCollection Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CategoryCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DisplayCategory[] displayCategoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public DisplayCategory[] DisplayCategories {
            get {
                return this.displayCategoriesField;
            }
            set {
                this.displayCategoriesField = value;
                this.RaisePropertyChanged("DisplayCategories");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DisplayCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventoryItemData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventoryItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemExtended))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseData : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InventoryItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemExtended))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InventoryItemData : BaseData {
        
        private System.Data.DataSet sourceDataSetField;
        
        private string itemIdField;
        
        private string descriptionField;
        
        private string description2Field;
        
        private string description3Field;
        
        private string description4Field;
        
        private string description5Field;
        
        private string description6Field;
        
        private string description7Field;
        
        private decimal webPriceField;
        
        private bool isESellableField;
        
        private bool eSpecialField;
        
        private bool eFeaturedField;
        
        private bool eNoShipChargeField;
        
        private string eTemplateField;
        
        private string eLinkField;
        
        private string stkumidField;
        
        private string sunmsidField;
        
        private string imageSmField;
        
        private string imageMdField;
        
        private string imageLgField;
        
        private string imageXLField;
        
        private decimal priceField;
        
        private string taxCodeField;
        
        private decimal weightField;
        
        private string memoField;
        
        private bool dropShipField;
        
        private decimal msrpField;
        
        private System.DateTime addDateField;
        
        private decimal ySalesQtyField;
        
        private string eStyleField;
        
        private string eStyle1Field;
        
        private string eStyle2Field;
        
        private decimal sumfactField;
        
        private decimal pumfactField;
        
        private string punmsidField;
        
        private decimal avgCostField;
        
        private int listOrderField;
        
        private int viewOrderField;
        
        private bool recurringField;
        
        private decimal eLengthField;
        
        private decimal eWidthField;
        
        private decimal eHeightField;
        
        private bool noShipCalcField;
        
        private bool resellField;
        
        private decimal onHandField;
        
        private decimal sOAllocatedField;
        
        private decimal leadTimeField;
        
        private decimal wOAllocatedField;
        
        private bool soloPackField;
        
        private int orderingInstructionIdField;
        
        private string itemClassField;
        
        private bool phantomField;
        
        private bool discontinuedField;
        
        private string webTypeField;
        
        private bool isKitField;
        
        private decimal buildQuantityField;
        
        private string manufacturerField;
        
        private string manufacturerNoField;
        
        private string altItem1Field;
        
        private string altItem2Field;
        
        private string altItem1TypeField;
        
        private string altItem2TypeField;
        
        private int rawSearchRankField;
        
        private int searchRankField;
        
        private string searchSourceField;
        
        private string searchSourcesField;
        
        private bool altsAvailableField;
        
        private string countryOriginField;
        
        private string harmtCodeField;
        
        private decimal leadtimeLowField;
        
        private decimal leadtimeHighField;
        
        private string newPriceField;
        
        private int pOQuantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Data.DataSet SourceDataSet {
            get {
                return this.sourceDataSetField;
            }
            set {
                this.sourceDataSetField = value;
                this.RaisePropertyChanged("SourceDataSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("ItemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description2 {
            get {
                return this.description2Field;
            }
            set {
                this.description2Field = value;
                this.RaisePropertyChanged("Description2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description3 {
            get {
                return this.description3Field;
            }
            set {
                this.description3Field = value;
                this.RaisePropertyChanged("Description3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description4 {
            get {
                return this.description4Field;
            }
            set {
                this.description4Field = value;
                this.RaisePropertyChanged("Description4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Description5 {
            get {
                return this.description5Field;
            }
            set {
                this.description5Field = value;
                this.RaisePropertyChanged("Description5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Description6 {
            get {
                return this.description6Field;
            }
            set {
                this.description6Field = value;
                this.RaisePropertyChanged("Description6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Description7 {
            get {
                return this.description7Field;
            }
            set {
                this.description7Field = value;
                this.RaisePropertyChanged("Description7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal WebPrice {
            get {
                return this.webPriceField;
            }
            set {
                this.webPriceField = value;
                this.RaisePropertyChanged("WebPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool isESellable {
            get {
                return this.isESellableField;
            }
            set {
                this.isESellableField = value;
                this.RaisePropertyChanged("isESellable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool ESpecial {
            get {
                return this.eSpecialField;
            }
            set {
                this.eSpecialField = value;
                this.RaisePropertyChanged("ESpecial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool EFeatured {
            get {
                return this.eFeaturedField;
            }
            set {
                this.eFeaturedField = value;
                this.RaisePropertyChanged("EFeatured");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool ENoShipCharge {
            get {
                return this.eNoShipChargeField;
            }
            set {
                this.eNoShipChargeField = value;
                this.RaisePropertyChanged("ENoShipCharge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ETemplate {
            get {
                return this.eTemplateField;
            }
            set {
                this.eTemplateField = value;
                this.RaisePropertyChanged("ETemplate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ELink {
            get {
                return this.eLinkField;
            }
            set {
                this.eLinkField = value;
                this.RaisePropertyChanged("ELink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string stkumid {
            get {
                return this.stkumidField;
            }
            set {
                this.stkumidField = value;
                this.RaisePropertyChanged("stkumid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string sunmsid {
            get {
                return this.sunmsidField;
            }
            set {
                this.sunmsidField = value;
                this.RaisePropertyChanged("sunmsid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ImageSm {
            get {
                return this.imageSmField;
            }
            set {
                this.imageSmField = value;
                this.RaisePropertyChanged("ImageSm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ImageMd {
            get {
                return this.imageMdField;
            }
            set {
                this.imageMdField = value;
                this.RaisePropertyChanged("ImageMd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ImageLg {
            get {
                return this.imageLgField;
            }
            set {
                this.imageLgField = value;
                this.RaisePropertyChanged("ImageLg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ImageXL {
            get {
                return this.imageXLField;
            }
            set {
                this.imageXLField = value;
                this.RaisePropertyChanged("ImageXL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
                this.RaisePropertyChanged("TaxCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool DropShip {
            get {
                return this.dropShipField;
            }
            set {
                this.dropShipField = value;
                this.RaisePropertyChanged("DropShip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public decimal Msrp {
            get {
                return this.msrpField;
            }
            set {
                this.msrpField = value;
                this.RaisePropertyChanged("Msrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public System.DateTime AddDate {
            get {
                return this.addDateField;
            }
            set {
                this.addDateField = value;
                this.RaisePropertyChanged("AddDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public decimal YSalesQty {
            get {
                return this.ySalesQtyField;
            }
            set {
                this.ySalesQtyField = value;
                this.RaisePropertyChanged("YSalesQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string EStyle {
            get {
                return this.eStyleField;
            }
            set {
                this.eStyleField = value;
                this.RaisePropertyChanged("EStyle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string EStyle1 {
            get {
                return this.eStyle1Field;
            }
            set {
                this.eStyle1Field = value;
                this.RaisePropertyChanged("EStyle1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string EStyle2 {
            get {
                return this.eStyle2Field;
            }
            set {
                this.eStyle2Field = value;
                this.RaisePropertyChanged("EStyle2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public decimal sumfact {
            get {
                return this.sumfactField;
            }
            set {
                this.sumfactField = value;
                this.RaisePropertyChanged("sumfact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public decimal pumfact {
            get {
                return this.pumfactField;
            }
            set {
                this.pumfactField = value;
                this.RaisePropertyChanged("pumfact");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string punmsid {
            get {
                return this.punmsidField;
            }
            set {
                this.punmsidField = value;
                this.RaisePropertyChanged("punmsid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public decimal AvgCost {
            get {
                return this.avgCostField;
            }
            set {
                this.avgCostField = value;
                this.RaisePropertyChanged("AvgCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public int ListOrder {
            get {
                return this.listOrderField;
            }
            set {
                this.listOrderField = value;
                this.RaisePropertyChanged("ListOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public int ViewOrder {
            get {
                return this.viewOrderField;
            }
            set {
                this.viewOrderField = value;
                this.RaisePropertyChanged("ViewOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public bool Recurring {
            get {
                return this.recurringField;
            }
            set {
                this.recurringField = value;
                this.RaisePropertyChanged("Recurring");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public decimal ELength {
            get {
                return this.eLengthField;
            }
            set {
                this.eLengthField = value;
                this.RaisePropertyChanged("ELength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public decimal EWidth {
            get {
                return this.eWidthField;
            }
            set {
                this.eWidthField = value;
                this.RaisePropertyChanged("EWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public decimal EHeight {
            get {
                return this.eHeightField;
            }
            set {
                this.eHeightField = value;
                this.RaisePropertyChanged("EHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public bool NoShipCalc {
            get {
                return this.noShipCalcField;
            }
            set {
                this.noShipCalcField = value;
                this.RaisePropertyChanged("NoShipCalc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public bool Resell {
            get {
                return this.resellField;
            }
            set {
                this.resellField = value;
                this.RaisePropertyChanged("Resell");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public decimal OnHand {
            get {
                return this.onHandField;
            }
            set {
                this.onHandField = value;
                this.RaisePropertyChanged("OnHand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public decimal SOAllocated {
            get {
                return this.sOAllocatedField;
            }
            set {
                this.sOAllocatedField = value;
                this.RaisePropertyChanged("SOAllocated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public decimal LeadTime {
            get {
                return this.leadTimeField;
            }
            set {
                this.leadTimeField = value;
                this.RaisePropertyChanged("LeadTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public decimal WOAllocated {
            get {
                return this.wOAllocatedField;
            }
            set {
                this.wOAllocatedField = value;
                this.RaisePropertyChanged("WOAllocated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public bool SoloPack {
            get {
                return this.soloPackField;
            }
            set {
                this.soloPackField = value;
                this.RaisePropertyChanged("SoloPack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public int OrderingInstructionId {
            get {
                return this.orderingInstructionIdField;
            }
            set {
                this.orderingInstructionIdField = value;
                this.RaisePropertyChanged("OrderingInstructionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string ItemClass {
            get {
                return this.itemClassField;
            }
            set {
                this.itemClassField = value;
                this.RaisePropertyChanged("ItemClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public bool Phantom {
            get {
                return this.phantomField;
            }
            set {
                this.phantomField = value;
                this.RaisePropertyChanged("Phantom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public bool Discontinued {
            get {
                return this.discontinuedField;
            }
            set {
                this.discontinuedField = value;
                this.RaisePropertyChanged("Discontinued");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string WebType {
            get {
                return this.webTypeField;
            }
            set {
                this.webTypeField = value;
                this.RaisePropertyChanged("WebType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public bool IsKit {
            get {
                return this.isKitField;
            }
            set {
                this.isKitField = value;
                this.RaisePropertyChanged("IsKit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public decimal BuildQuantity {
            get {
                return this.buildQuantityField;
            }
            set {
                this.buildQuantityField = value;
                this.RaisePropertyChanged("BuildQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("Manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string ManufacturerNo {
            get {
                return this.manufacturerNoField;
            }
            set {
                this.manufacturerNoField = value;
                this.RaisePropertyChanged("ManufacturerNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string AltItem1 {
            get {
                return this.altItem1Field;
            }
            set {
                this.altItem1Field = value;
                this.RaisePropertyChanged("AltItem1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string AltItem2 {
            get {
                return this.altItem2Field;
            }
            set {
                this.altItem2Field = value;
                this.RaisePropertyChanged("AltItem2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string AltItem1Type {
            get {
                return this.altItem1TypeField;
            }
            set {
                this.altItem1TypeField = value;
                this.RaisePropertyChanged("AltItem1Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string AltItem2Type {
            get {
                return this.altItem2TypeField;
            }
            set {
                this.altItem2TypeField = value;
                this.RaisePropertyChanged("AltItem2Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public int RawSearchRank {
            get {
                return this.rawSearchRankField;
            }
            set {
                this.rawSearchRankField = value;
                this.RaisePropertyChanged("RawSearchRank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public int SearchRank {
            get {
                return this.searchRankField;
            }
            set {
                this.searchRankField = value;
                this.RaisePropertyChanged("SearchRank");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string SearchSource {
            get {
                return this.searchSourceField;
            }
            set {
                this.searchSourceField = value;
                this.RaisePropertyChanged("SearchSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string SearchSources {
            get {
                return this.searchSourcesField;
            }
            set {
                this.searchSourcesField = value;
                this.RaisePropertyChanged("SearchSources");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public bool AltsAvailable {
            get {
                return this.altsAvailableField;
            }
            set {
                this.altsAvailableField = value;
                this.RaisePropertyChanged("AltsAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string CountryOrigin {
            get {
                return this.countryOriginField;
            }
            set {
                this.countryOriginField = value;
                this.RaisePropertyChanged("CountryOrigin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string HarmtCode {
            get {
                return this.harmtCodeField;
            }
            set {
                this.harmtCodeField = value;
                this.RaisePropertyChanged("HarmtCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public decimal LeadtimeLow {
            get {
                return this.leadtimeLowField;
            }
            set {
                this.leadtimeLowField = value;
                this.RaisePropertyChanged("LeadtimeLow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public decimal LeadtimeHigh {
            get {
                return this.leadtimeHighField;
            }
            set {
                this.leadtimeHighField = value;
                this.RaisePropertyChanged("LeadtimeHigh");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public string NewPrice {
            get {
                return this.newPriceField;
            }
            set {
                this.newPriceField = value;
                this.RaisePropertyChanged("NewPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public int POQuantity {
            get {
                return this.pOQuantityField;
            }
            set {
                this.pOQuantityField = value;
                this.RaisePropertyChanged("POQuantity");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemExtended))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InventoryItem : InventoryItemData {
        
        private string priceDisplayField;
        
        private string priceDisplayTypeField;
        
        private decimal displayPriceField;
        
        private string webPriceDisplayField;
        
        private bool noLongerAvailableField;
        
        private bool replacedField;
        
        private bool specialOrderField;
        
        private bool refurbishedField;
        
        private bool proprietaryField;
        
        private bool eSellableField;
        
        private int pagingControlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PriceDisplay {
            get {
                return this.priceDisplayField;
            }
            set {
                this.priceDisplayField = value;
                this.RaisePropertyChanged("PriceDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PriceDisplayType {
            get {
                return this.priceDisplayTypeField;
            }
            set {
                this.priceDisplayTypeField = value;
                this.RaisePropertyChanged("PriceDisplayType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal DisplayPrice {
            get {
                return this.displayPriceField;
            }
            set {
                this.displayPriceField = value;
                this.RaisePropertyChanged("DisplayPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string WebPriceDisplay {
            get {
                return this.webPriceDisplayField;
            }
            set {
                this.webPriceDisplayField = value;
                this.RaisePropertyChanged("WebPriceDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool NoLongerAvailable {
            get {
                return this.noLongerAvailableField;
            }
            set {
                this.noLongerAvailableField = value;
                this.RaisePropertyChanged("NoLongerAvailable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool Replaced {
            get {
                return this.replacedField;
            }
            set {
                this.replacedField = value;
                this.RaisePropertyChanged("Replaced");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool SpecialOrder {
            get {
                return this.specialOrderField;
            }
            set {
                this.specialOrderField = value;
                this.RaisePropertyChanged("SpecialOrder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Refurbished {
            get {
                return this.refurbishedField;
            }
            set {
                this.refurbishedField = value;
                this.RaisePropertyChanged("Refurbished");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool Proprietary {
            get {
                return this.proprietaryField;
            }
            set {
                this.proprietaryField = value;
                this.RaisePropertyChanged("Proprietary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool ESellable {
            get {
                return this.eSellableField;
            }
            set {
                this.eSellableField = value;
                this.RaisePropertyChanged("ESellable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int PagingControl {
            get {
                return this.pagingControlField;
            }
            set {
                this.pagingControlField = value;
                this.RaisePropertyChanged("PagingControl");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemExtended : InventoryItem {
        
        private decimal kitBuildableField;
        
        private string priceChartDisplayField;
        
        private object priceChartsField;
        
        private int cartQuantityField;
        
        private string imageNameField;
        
        private CompMfgCollection manufacturerInfoField;
        
        private ItemExtended[] componentItemsField;
        
        private bool deFactoDiscontinuedField;
        
        private bool proprietaryNoneOnHandField;
        
        private decimal buildableQuantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal KitBuildable {
            get {
                return this.kitBuildableField;
            }
            set {
                this.kitBuildableField = value;
                this.RaisePropertyChanged("KitBuildable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PriceChartDisplay {
            get {
                return this.priceChartDisplayField;
            }
            set {
                this.priceChartDisplayField = value;
                this.RaisePropertyChanged("PriceChartDisplay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object PriceCharts {
            get {
                return this.priceChartsField;
            }
            set {
                this.priceChartsField = value;
                this.RaisePropertyChanged("PriceCharts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int CartQuantity {
            get {
                return this.cartQuantityField;
            }
            set {
                this.cartQuantityField = value;
                this.RaisePropertyChanged("CartQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ImageName {
            get {
                return this.imageNameField;
            }
            set {
                this.imageNameField = value;
                this.RaisePropertyChanged("ImageName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public CompMfgCollection ManufacturerInfo {
            get {
                return this.manufacturerInfoField;
            }
            set {
                this.manufacturerInfoField = value;
                this.RaisePropertyChanged("ManufacturerInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public ItemExtended[] ComponentItems {
            get {
                return this.componentItemsField;
            }
            set {
                this.componentItemsField = value;
                this.RaisePropertyChanged("ComponentItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool DeFactoDiscontinued {
            get {
                return this.deFactoDiscontinuedField;
            }
            set {
                this.deFactoDiscontinuedField = value;
                this.RaisePropertyChanged("DeFactoDiscontinued");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool ProprietaryNoneOnHand {
            get {
                return this.proprietaryNoneOnHandField;
            }
            set {
                this.proprietaryNoneOnHandField = value;
                this.RaisePropertyChanged("ProprietaryNoneOnHand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal BuildableQuantity {
            get {
                return this.buildableQuantityField;
            }
            set {
                this.buildableQuantityField = value;
                this.RaisePropertyChanged("BuildableQuantity");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompMfgCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CompMfg[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public CompMfg[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CompMfg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string compMfgNameField;
        
        private string compMfgPartNoField;
        
        private CompMfgType compMfgTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompMfgName {
            get {
                return this.compMfgNameField;
            }
            set {
                this.compMfgNameField = value;
                this.RaisePropertyChanged("CompMfgName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompMfgPartNo {
            get {
                return this.compMfgPartNoField;
            }
            set {
                this.compMfgPartNoField = value;
                this.RaisePropertyChanged("CompMfgPartNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public CompMfgType CompMfgType {
            get {
                return this.compMfgTypeField;
            }
            set {
                this.compMfgTypeField = value;
                this.RaisePropertyChanged("CompMfgType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CompMfgType {
        
        /// <remarks/>
        Competitor,
        
        /// <remarks/>
        Manufacturer,
        
        /// <remarks/>
        Supplier,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemIdField;
        
        private string descriptionField;
        
        private string description2Field;
        
        private string description3Field;
        
        private string description4Field;
        
        private bool eSellableField;
        
        private decimal weightField;
        
        private string memoField;
        
        private bool dropShipField;
        
        private bool phantomField;
        
        private string manufacturerField;
        
        private string manufacturerNoField;
        
        private string webTypeField;
        
        private string altItem1Field;
        
        private string altItem2Field;
        
        private string altItem1TypeField;
        
        private string altItem2TypeField;
        
        private bool discontinuedField;
        
        private bool isKitField;
        
        private decimal priceField;
        
        private Item[] componentItemsField;
        
        private CompMfgCollection manufacturerInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemId {
            get {
                return this.itemIdField;
            }
            set {
                this.itemIdField = value;
                this.RaisePropertyChanged("ItemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description2 {
            get {
                return this.description2Field;
            }
            set {
                this.description2Field = value;
                this.RaisePropertyChanged("Description2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description3 {
            get {
                return this.description3Field;
            }
            set {
                this.description3Field = value;
                this.RaisePropertyChanged("Description3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description4 {
            get {
                return this.description4Field;
            }
            set {
                this.description4Field = value;
                this.RaisePropertyChanged("Description4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool ESellable {
            get {
                return this.eSellableField;
            }
            set {
                this.eSellableField = value;
                this.RaisePropertyChanged("ESellable");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool DropShip {
            get {
                return this.dropShipField;
            }
            set {
                this.dropShipField = value;
                this.RaisePropertyChanged("DropShip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Phantom {
            get {
                return this.phantomField;
            }
            set {
                this.phantomField = value;
                this.RaisePropertyChanged("Phantom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                this.manufacturerField = value;
                this.RaisePropertyChanged("Manufacturer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ManufacturerNo {
            get {
                return this.manufacturerNoField;
            }
            set {
                this.manufacturerNoField = value;
                this.RaisePropertyChanged("ManufacturerNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string WebType {
            get {
                return this.webTypeField;
            }
            set {
                this.webTypeField = value;
                this.RaisePropertyChanged("WebType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string AltItem1 {
            get {
                return this.altItem1Field;
            }
            set {
                this.altItem1Field = value;
                this.RaisePropertyChanged("AltItem1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AltItem2 {
            get {
                return this.altItem2Field;
            }
            set {
                this.altItem2Field = value;
                this.RaisePropertyChanged("AltItem2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string AltItem1Type {
            get {
                return this.altItem1TypeField;
            }
            set {
                this.altItem1TypeField = value;
                this.RaisePropertyChanged("AltItem1Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AltItem2Type {
            get {
                return this.altItem2TypeField;
            }
            set {
                this.altItem2TypeField = value;
                this.RaisePropertyChanged("AltItem2Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool Discontinued {
            get {
                return this.discontinuedField;
            }
            set {
                this.discontinuedField = value;
                this.RaisePropertyChanged("Discontinued");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool IsKit {
            get {
                return this.isKitField;
            }
            set {
                this.isKitField = value;
                this.RaisePropertyChanged("IsKit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=20)]
        public Item[] ComponentItems {
            get {
                return this.componentItemsField;
            }
            set {
                this.componentItemsField = value;
                this.RaisePropertyChanged("ComponentItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public CompMfgCollection ManufacturerInfo {
            get {
                return this.manufacturerInfoField;
            }
            set {
                this.manufacturerInfoField = value;
                this.RaisePropertyChanged("ManufacturerInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Category : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string categoryIdField;
        
        private Item[] itemsField;
        
        private Category[] subCategoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
                this.RaisePropertyChanged("CategoryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Item[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
                this.RaisePropertyChanged("Items");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Category[] SubCategories {
            get {
                return this.subCategoriesField;
            }
            set {
                this.subCategoriesField = value;
                this.RaisePropertyChanged("SubCategories");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemsInCategoryCollection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Category[] categoriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Category[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("Categories");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        private LoginResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public LoginResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum LoginResult {
        
        /// <remarks/>
        UserNotFound,
        
        /// <remarks/>
        NoCustomerForUser,
        
        /// <remarks/>
        CustomerInactive,
        
        /// <remarks/>
        SalesRepModeNotActive,
        
        /// <remarks/>
        CreditHold,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        CustomerDenied,
        
        /// <remarks/>
        NonPurchasingCustomer,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SingleItemResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemsInCategoryResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CategoryResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuthenticationResult authenticationField;
        
        private bool errorField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuthenticationResult Authentication {
            get {
                return this.authenticationField;
            }
            set {
                this.authenticationField = value;
                this.RaisePropertyChanged("Authentication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleItemResponse : Response {
        
        private ItemExtended detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ItemExtended Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ItemsInCategoryResponse : Response {
        
        private ItemsInCategoryCollection detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ItemsInCategoryCollection Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("Detail");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HorizonServiceSoapChannel : TestHorizonWebService.HorizonServiceDevo.HorizonServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HorizonServiceSoapClient : System.ServiceModel.ClientBase<TestHorizonWebService.HorizonServiceDevo.HorizonServiceSoap>, TestHorizonWebService.HorizonServiceDevo.HorizonServiceSoap {
        
        public HorizonServiceSoapClient() {
        }
        
        public HorizonServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HorizonServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorizonServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorizonServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestHorizonWebService.HorizonServiceDevo.CategoryResponse CategoryList(string pUser, string pPassword, string pCustno) {
            return base.Channel.CategoryList(pUser, pPassword, pCustno);
        }
        
        public TestHorizonWebService.HorizonServiceDevo.Response AliveCheck() {
            return base.Channel.AliveCheck();
        }
        
        public TestHorizonWebService.HorizonServiceDevo.ItemsInCategoryResponse Items(string pCategoryId, string pUser, string pPassword, string pCustno) {
            return base.Channel.Items(pCategoryId, pUser, pPassword, pCustno);
        }
        
        public TestHorizonWebService.HorizonServiceDevo.SingleItemResponse Item(string pItemId, string pUserId, string pPassword, string pCustno) {
            return base.Channel.Item(pItemId, pUserId, pPassword, pCustno);
        }
    }
}
